name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build

    - name: Copy built files to Github Pages
      run: |
        git config user.name 'GitHub Action'
        git config user.email 'action@github.com'
        git branch -f gh-pages HEAD
        git checkout gh-pages --
        date > public/date.txt
        git add --force public
        git commit -m "Build"
        git push -f origin `git subtree split -P dist`:refs/heads/gh-pages
